// <auto-generated />
namespace DDTBaiThucHanh486.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_class_person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_class_person));
        
        string IMigrationMetadata.Id
        {
            get { return "202203080104087_add_class_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
