// <auto-generated />
namespace DDTBaiTapLon486.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_clas_KhachHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_clas_KhachHang));
        
        string IMigrationMetadata.Id
        {
            get { return "202205300431181_alter_clas_KhachHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
