// <auto-generated />
namespace DDTBaiTapLon486.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_models));
        
        string IMigrationMetadata.Id
        {
            get { return "202205220312039_update_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
